//
//  UserViewModel.swift
//  OperationMeteor
//
//  Created by Richard Crichlow on 4/27/23.
//

import Foundation

class UserViewModel: ObservableObject {
    @Published var users: [User] = [
        User(id: UUID(), name: "Alice", shares: 30, firstName: "Alice", lastName: "Adams", email: "alice@example.com", phoneNumber: "555-111-1111", profileImageURL: "https://example.com/alice-profile.jpg", backgroundURL: "https://example.com/alice-background.jpg", bio: "Alice loves to cook and travel.", userId: "alice123", displayName: "AliceA"),
        User(id: UUID(), name: "Bob", shares: 25, firstName: "Bob", lastName: "Baker", email: "bob@example.com", phoneNumber: "555-222-2222", profileImageURL: "https://example.com/bob-profile.jpg", backgroundURL: "https://example.com/bob-background.jpg", bio: "Bob is a gardening enthusiast.", userId: "bob456", displayName: "BobB"),
        User(id: UUID(), name: "Jessie", shares: 26, firstName: "Jessie", lastName: "James", email: "jessie@example.com", phoneNumber: "555-777-0007", profileImageURL: "https://example.com/jessie-profile.jpg", backgroundURL: "https://example.com/jessie-background.jpg", bio: "Jessie is a professional dancer and a yoga enthusiast.", userId: "jessie107", displayName: "JessieJ"),
        User(id: UUID(), name: "Oscar", shares: 22, firstName: "Oscar", lastName: "Ortega", email: "oscar@example.com", phoneNumber: "555-888-0008", profileImageURL: "https://example.com/oscar-profile.jpg", backgroundURL: "https://example.com/oscar-background.jpg", bio: "Oscar is a software engineer who enjoys playing chess and solving puzzles.", userId: "oscar108", displayName: "OscarO"),
        User(id: UUID(), name: "Rita", shares: 17, firstName: "Rita", lastName: "Ramirez", email: "rita@example.com", phoneNumber: "555-999-0009", profileImageURL: "https://example.com/rita-profile.jpg", backgroundURL: "https://example.com/rita-background.jpg", bio: "Rita is a teacher who loves reading and writing poetry.", userId: "rita109", displayName: "RitaR"),
        User(id: UUID(), name: "Gavin", shares: 30, firstName: "Gavin", lastName: "Green", email: "gavin@example.com", phoneNumber: "555-000-0010", profileImageURL: "https://example.com/gavin-profile.jpg", backgroundURL: "https://example.com/gavin-background.jpg", bio: "Gavin is an architect who enjoys hiking and photography.", userId: "gavin110", displayName: "GavinG"),
        User(id: UUID(), name: "Natalie", shares: 31, firstName: "Natalie", lastName: "Nelson", email: "natalie@example.com", phoneNumber: "555-111-0011", profileImageURL: "https://example.com/natalie-profile.jpg", backgroundURL: "https://example.com/natalie-background.jpg", bio: "Natalie is a doctor who loves to travel and learn new languages.", userId: "natalie111", displayName: "NatalieN"),
        User(id: UUID(), name: "Peter", shares: 24, firstName: "Peter", lastName: "Parker", email: "peter@example.com", phoneNumber: "555-222-0012", profileImageURL: "https://example.com/peter-profile.jpg", backgroundURL: "https://example.com/peter-background.jpg", bio: "Peter is a journalist who enjoys photography and exploring the city.", userId: "peter112", displayName: "PeterP"),
        User(id: UUID(), name: "Samantha", shares: 28, firstName: "Samantha", lastName: "Smith", email: "samantha@example.com", phoneNumber: "555-333-0013", profileImageURL: "https://example.com/samantha-profile.jpg", backgroundURL: "https://example.com/samantha-background.jpg", bio: "Samantha is a graphic designer who enjoys painting and photography.", userId: "samantha113", displayName: "SamanthaS"),
        User(id: UUID(), name: "Victor", shares: 20, firstName: "Victor", lastName: "Vargas", email: "victor@example.com", phoneNumber: "555-444-0014", profileImageURL: "https://example.com/victor-profile.jpg", backgroundURL: "https://example.com/victor-background.jpg", bio: "Victor is a musician who loves to compose and perform his own music.", userId: "victor114", displayName: "VictorV"),
        User(id: UUID(), name: "Wendy", shares: 32, firstName: "Wendy", lastName: "Williams", email: "wendy@example.com", phoneNumber: "555-555-0015", profileImageURL: "https://example.com/wendy-profile.jpg", backgroundURL: "https://example.com/wendy-background.jpg", bio: "Wendy is a marketing professional who enjoys running and swimming.", userId: "wendy115", displayName: "WendyW"),
        User(id: UUID(), name: "Victoria", shares: 40, firstName: "Victoria", lastName: "Vance", email: "victoria@example.com", phoneNumber: "555-111-0001", profileImageURL: "https://example.com/victoria-profile.jpg", backgroundURL: "https://example.com/victoria-background.jpg", bio: "Victoria is passionate about photography and fashion.", userId: "victoria101", displayName: "VictoriaV"),
        User(id: UUID(), name: "Walter", shares: 32, firstName: "Walter", lastName: "White", email: "walter@example.com", phoneNumber: "555-222-0002", profileImageURL: "https://example.com/walter-profile.jpg", backgroundURL: "https://example.com/walter-background.jpg", bio: "Walter is a software developer who loves playing the guitar.", userId: "walter102", displayName: "WalterW"),
        User(id: UUID(), name: "Xander", shares: 18, firstName: "Xander", lastName: "Xylophone", email: "xander@example.com", phoneNumber: "555-333-0003", profileImageURL: "https://example.com/xander-profile.jpg", backgroundURL: "https://example.com/xander-background.jpg", bio: "Xander enjoys hiking and exploring nature.", userId: "xander103", displayName: "XanderX"),
        User(id: UUID(), name: "Quincy", shares: 29, firstName: "Quincy", lastName: "Quinn", email: "quincy@example.com", phoneNumber: "555-444-0004", profileImageURL: "https://example.com/quincy-profile.jpg", backgroundURL: "https://example.com/quincy-background.jpg", bio: "Quincy is a finance expert and an amateur chef.", userId: "quincy104", displayName: "QuincyQ"),
        User(id: UUID(), name: "Ursula", shares: 27, firstName: "Ursula", lastName: "Underwood", email: "ursula@example.com", phoneNumber: "555-555-0005", profileImageURL: "https://example.com/ursula-profile.jpg", backgroundURL: "https://example.com/ursula-background.jpg", bio: "Ursula is a graphic designer who loves painting and drawing.", userId: "ursula105", displayName: "UrsulaU"),
        User(id: UUID(), name: "Yvette", shares: 22, firstName: "Yvette", lastName: "Young", email: "yvette@example.com", phoneNumber: "555-999-9999", profileImageURL: "https://example.com/yvette-profile.jpg", backgroundURL: "https://example.com/yvette-background.jpg", bio: "Yvette enjoys reading and writing.", userId: "yvette789", displayName: "YvetteY"),
        User(id: UUID(), name: "Zachary", shares: 45, firstName: "Zachary", lastName: "Zimmerman", email: "zachary@example.com", phoneNumber: "555-000-0000", profileImageURL: "https://example.com/zachary-profile.jpg", backgroundURL: "https://example.com/zachary-background.jpg", bio: "Zachary is a tech enthusiast and an avid gamer.", userId: "zachary789", displayName: "ZacharyZ")
    ]
    
    // Add functions to fetch and display user rankings based on sharing activity from a server or local storage
}
